server:
  port: 8092

spring:
  application:
    name: 'order'
        
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/api/auth/user

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 # Fuse service request timeout